CREATE TABLE areas(
    area_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    area_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE subareas(
    subarea_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    area_id INTEGER NOT NULL, 
    subarea_name VARCHAR(50) NOT NULL,

    FOREIGN KEY(area_id)
        REFERENCES areas(area_id),
    
    UNIQUE(area_id, subarea_name)
);

CREATE TABLE locales(
    locale_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subarea_id INTEGER NOT NULL,
    locale_name VARCHAR(50) NOT NULL,
    country VARCHAR(50) NOT NULL,

    FOREIGN KEY(subarea_id)
        REFERENCES subareas(subarea_id),

    UNIQUE(locale_name, country)
);

CREATE TABLE flocks(
    flock_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    locale_id INTEGER NOT NULL,
    flock_name VARCHAR(50) NOT NULL,

    FOREIGN KEY(locale_id)
        REFERENCES locales(locale_id),

    UNIQUE(locale_id, flock_name)
);

CREATE TABLE positions(
    position_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    position_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE assigned_positions(
    positions_id INTEGER PRIMARY KEY,
    position_id INTEGER NOT NULL,

    FOREIGN KEY(position_id)
        REFERENCES positions(position_id)
);

CREATE TABLE members(
    member_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    flock_id INTEGER NOT NULL,
    positions_id INTEGER NOT NULL UNIQUE,
    privilege_level SMALLINT NOT NULL, -- range(0, 4)
    username VARCHAR(50) UNIQUE NOT NULL,
    passwd VARCHAR(64) NOT NULL,
    salt VARCHAR(16) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    middlename VARCHAR(50),
    surname VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    home_address VARCHAR(100),
    is_registered BOOLEAN NOT NULL,
    registration_date TIMESTAMP NOT NULL,

    FOREIGN KEY(flock_id)
        REFERENCES flocks(flock_id),
    FOREIGN KEY(positions_id)
        REFERENCES assigned_positions(positions_id),

    CHECK(privilege_level BETWEEN 0 AND 4)
);

CREATE TABLE events(
    event_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    locale_id INTEGER NOT NULL,
    event_name VARCHAR(50) NOT NULL,

    FOREIGN KEY(locale_id)
        REFERENCES locales(locale_id),

    UNIQUE(locale_id, event_name)
);

CREATE TABLE attendance(
    attendance_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    member_id INTEGER NOT NULL,
    event_id INTEGER NOT NULL,
    attendance_date DATE NOT NULL,
    attendance_time TIME WITH TIME ZONE NOT NULL,

    FOREIGN KEY(member_id)
        REFERENCES members(member_id),
    FOREIGN KEY(event_id)
        REFERENCES events(event_id),

    UNIQUE(member_id, event_id, attendance_date)
);
